apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORTONE_SECRET: ""
  JWT_KEY: "change-me"
  JWT_EXPIRE: "86400000"
  ADMIN_EMAIL: "administrator@example.com"
  ADMIN_NAME: "Administrator"
  ADMIN_ROLE: "ROLE_ADMIN"
  ADMIN_PASSWORD: "change-me"
  APP_FRONTEND_URL: "http://localhost"
  APP_BACKEND_URL: "http://localhost/api"
  APP_SECURE_COOKIE: "false"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  NAVER_CLIENT_ID: ""
  NAVER_CLIENT_SECRET: ""
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  MAIL_PORT: "587"
  MAIL_ID: ""
  MAIL_PASS: ""
  DB_SERVER: "org.mariadb.jdbc.Driver"
  DB_URL: "jdbc:mariadb://mariadb:3306/web"
  DB_ID: "web"
  DB_PASS: "change-me"
  STORAGE_PROVIDER: "minio"
  MINIO_API: "http://minio:9000"
  MINIO_NAME: "minioadmin"
  MINIO_SECRET: "minioadmin"
  MINIO_CLOUD_BUCKET: "waffle-cloud"
  MINIO_WORKSPACE_BUCKET: "waffle-workspace"
  MINIO_REGION: "us-east-1"
  S3AMAZON_API: ""
  S3AMAZON_NAME: ""
  S3AMAZON_SECRET: ""
  S3AMAZON_CLOUD_BUCKET: ""
  S3AMAZON_WORKSPACE_BUCKET: ""
  S3AMAZON_REGION: ""
  TZ: "Asia/Seoul"
